# Generated by Django 4.1.7 on 2023-04-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('dept_name', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('', 'Select status'), ('O', 'Ongoing'), ('C', 'Completed')], default='', max_length=1)),
                ('duration_year', models.IntegerField()),
                ('duration_month', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=0)),
            ],
        ),
    ]
