# Generated by Django 4.1.7 on 2023-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='allocated_funds',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
