# Generated by Django 4.1.7 on 2023-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=1)),
                ('transactee', models.CharField(max_length=200)),
                ('purpose', models.TextField(max_length=500)),
                ('date_of_transaction', models.DateField()),
                ('current_balance', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
