# Generated by Django 4.1.7 on 2023-04-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_of_admission',
            field=models.PositiveIntegerField(default=2023),
            preserve_default=False,
        ),
    ]
