# Generated by Django 4.1.7 on 2023-04-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_year_of_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_of_courses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
