# Generated by Django 4.1.7 on 2023-04-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_number_of_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='number_of_courses',
        ),
    ]
