# Generated by Django 4.1.7 on 2023-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_gradetally_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradetally',
            name='number_of_courses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
