# Generated by Django 4.1.7 on 2023-04-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_gradetally_number_of_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradetally',
            name='number_of_courses',
        ),
        migrations.AddField(
            model_name='grades',
            name='number_of_courses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
