# Generated by Django 4.1.7 on 2023-04-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_gradetally_number_of_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(10, 'EX'), (9, 'A'), (8, 'B'), (7, 'C'), (6, 'D'), (5, 'P'), (0, 'F')], null=True),
        ),
    ]
