# Generated by Django 4.1.7 on 2023-04-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_grades_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('semester_number', 'subject')},
        ),
    ]
