# Generated by Django 4.1.7 on 2023-04-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_student_number_of_courses'),
        ('courses', '0007_alter_grades_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(10, 'EX'), (9, 'A'), (8, 'B'), (7, 'C'), (6, 'D'), (5, 'P'), (0, 'F')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gradetally',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_tally', to='accounts.student'),
        ),
        migrations.AlterUniqueTogether(
            name='gradetally',
            unique_together={('semester_number', 'student')},
        ),
    ]
