# Generated by Django 4.1.7 on 2023-04-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_grades_grade_alter_gradetally_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(10, 'EX'), (9, 'A'), (8, 'B'), (7, 'C'), (6, 'D'), (5, 'P'), (0, 'F'), (-1, 'R')], default=-1, null=True),
        ),
    ]
