# Generated by Django 4.1.7 on 2023-04-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_student_number_of_courses'),
        ('courses', '0009_alter_grades_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('semester_number', 'student', 'subject')},
        ),
    ]
