# Generated by Django 4.1.7 on 2023-04-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('pub_title', models.CharField(max_length=100, unique=True)),
                ('pub_author', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
